import { Workflow } from "../../service/workflow/WorkflowModel";
import { JDBC_TYPE } from "../../utils/constant";

// Mock function to simulate fetching data from API
export const mockFetchPendingTasks = async () => {
  return [
    {
      taskInstanceId: "1",
      workflowInstanceId: "wf1",
      addedOn: "2025-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "2",
      workflowInstanceId: "wf1",
      addedOn: "2026-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "3",
      workflowInstanceId: "wf1",
      addedOn: "2012-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "4",
      workflowInstanceId: "wf1",
      addedOn: "2013-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "5",
      workflowInstanceId: "wf1",
      addedOn: "2014-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "6",
      workflowInstanceId: "wf1",
      addedOn: "2015-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "7",
      workflowInstanceId: "wf1",
      addedOn: "2015-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "8",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "9",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "10",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "11",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "12",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "13",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "14",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "15",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "16",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "17",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "REVIEW",
      workflowI18Name: "REQUEST_VACATION",
      userDisplayName: "John Doe",
      tenantI18Name: "MAIN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: true,
      tokenId: 5678, // Add tokenId for the mock
    },
    {
      taskInstanceId: "18",
      workflowInstanceId: "wf1",
      addedOn: "2024-10-20T12:00:00Z",
      addedBy: "John Doe",
      savedOn: "2024-10-21T12:00:00Z",
      savedBy: "Jane Doe",
      committedOn: "2024-10-21T12:00:00Z",
      committedBy: "Admin",
      statusInId: "status1",
      statusOutId: "status2",
      tenantId: "tenant1",
      nextTenantId: "tenant2",
      nextTaskTypeId: "taskType1",
      taskTypeId: "task1",
      data: [1, 2],
      note: "Note 1",
      selectedTaskStatus: {
        id: "status1",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      businessErrorMessage: "No error",
      statuses: {},
      variables: {},
      variablesByName: {},
      taskI18Name: "CHECK_ATTACHMENTS",
      workflowI18Name: "REQUEST_LEAVE",
      userDisplayName: "John Doe",
      tenantI18Name: "DOWNTOWN_OFFICE",
      statusInDesc: "In Progress",
      loadedByOwner: false,
      tokenId: 5678, // Add tokenId for the mock
    },
  ];
};

export const mockFetchWorkflows = (): Promise<Workflow[]> => {
  return new Promise((resolve) => {
    const mockData: Workflow[] = [
      { id: "1", name: "REQUEST_VACATION", tokenId: 101 },
      { id: "2", name: "REQUEST_LEAVE", tokenId: 102 },
      { id: "3", name: "REQUEST_COMPENSATION", tokenId: 103 },
      { id: "4", name: "REQUEST_VACATION", tokenId: 104 },
      { id: "5", name: "REQUEST_LEAVE", tokenId: 105 },
      { id: "6", name: "REQUEST_LEAVE", tokenId: 102 },
      { id: "7", name: "REQUEST_COMPENSATION", tokenId: 103 },
      { id: "8", name: "REQUEST_VACATION", tokenId: 104 },
      { id: "9", name: "REQUEST_LEAVE", tokenId: 105 },
      { id: "10", name: "REQUEST_VACATION", tokenId: 104 },
      { id: "11", name: "REQUEST_LEAVE", tokenId: 105 },
    ];
    resolve(mockData);
  });
};

export function getMockWorkflowResponse() {
  return {
    taskInstanceId: "task_1234",
    workflowInstanceId: "workflow_5678",
    addedOn: new Date().toISOString(),
    addedBy: "user_abc",
    savedOn: new Date().toISOString(),
    savedBy: "user_xyz",
    committedOn: new Date().toISOString(),
    committedBy: "user_abc",
    statusInId: "status_in_001",
    statusOutId: "status_out_002",
    tenantId: "tenant_1001",
    nextTenantId: "tenant_1002",
    nextTaskTypeId: "taskType_003",
    taskTypeId: "taskType_001",
    data: [123456789, 987654321],
    note: "Sample note for the workflow task.",
    renderingStyle: "Wizard",
    selectedTaskStatus: {
      id: "status_1",
      i18nName: "Approved",
      startingTask: false,
      endingTask: true,
    },
    businessErrorMessage: "No errors found",
    statuses: {
      sit_4a7: {
        id: "status_4a7",
        i18nName: "In Progress",
        startingTask: true,
        endingTask: false,
      },
      sit6: {
        id: "status_6",
        i18nName: "Completed",
        startingTask: false,
        endingTask: true,
      },
    },
    variables: {
      exercitationbdd: {
        id: "var_1",
        tokenId: 101,
        i18nName: "First Name",
        type: 1,
        comboListName: "N/A",
        required: 1,
        hidden: 0,
        readOnly: 0,
        i18nGroupName: "Personal Details",
        mimeType: "text/plain",
        jdbcType: JDBC_TYPE.TextInput,
        auditable: 1,
        exitClassId: "exitClass_001",
        exitClassDataId: "exitData_001",
        instanceId: "inst_123",
        textValue: "John",
        numericValue: "1",
      },
      eu_3c: {
        id: "var_2",
        tokenId: 102,
        i18nName: "Last Name",
        type: 1,
        comboListName: "N/A",
        required: 1,
        hidden: 0,
        readOnly: 1,
        i18nGroupName: "Personal Details",
        mimeType: "text/plain",
        jdbcType: JDBC_TYPE.Label,
        auditable: 1,
        exitClassId: "exitClass_002",
        exitClassDataId: "exitData_002",
        instanceId: "inst_124",
        textValue: "Doe",
        numericValue: "1",
      },
      dolor8: {
        id: "var_3",
        tokenId: 103,
        i18nName: "Date of Birth",
        type: 1,
        comboListName: "N/A",
        required: 1,
        hidden: 0,
        readOnly: 0,
        i18nGroupName: "Personal Details",
        mimeType: "text/plain",
        jdbcType: JDBC_TYPE.DatePicker,
        auditable: 1,
        exitClassId: "exitClass_003",
        exitClassDataId: "exitData_003",
        instanceId: "inst_125",
        textValue: "1990-01-01",
        numericValue: "1",
      },
      Ut_b: {
        id: "var_4",
        tokenId: 104,
        i18nName: "Appointment Time",
        type: 1,
        comboListName: "N/A",
        required: 1,
        hidden: 0,
        readOnly: 0,
        i18nGroupName: "Appointment Details",
        mimeType: "text/plain",
        jdbcType: JDBC_TYPE.TimePicker,
        auditable: 1,
        exitClassId: "exitClass_004",
        exitClassDataId: "exitData_004",
        instanceId: "inst_126",
        textValue: "10:00 AM",
        numericValue: "1",
      },
      cb_field: {
        id: "var_5",
        tokenId: 105,
        i18nName: "Receive Updates",
        type: 1,
        comboListName: "N/A",
        required: 0,
        hidden: 0,
        readOnly: 0,
        i18nGroupName: "Preferences",
        mimeType: "text/plain",
        jdbcType: JDBC_TYPE.Checkbox,
        auditable: 1,
        exitClassId: "exitClass_005",
        exitClassDataId: "exitData_005",
        instanceId: "inst_127",
        textValue: "",
        numericValue: "1",
      },
      btn_action: {
        id: "var_6",
        tokenId: 106,
        i18nName: "Submit Button",
        type: 1,
        comboListName: "N/A",
        required: 0,
        hidden: 0,
        readOnly: 0,
        i18nGroupName: "Actions",
        mimeType: "text/plain",
        jdbcType: JDBC_TYPE.Button,
        auditable: 1,
        exitClassId: "exitClass_006",
        exitClassDataId: "exitData_006",
        instanceId: "inst_128",
        textValue: "Submit",
        numericValue: "",
      },
      decimal_input: {
        id: "var_7",
        tokenId: 107,
        i18nName: "Price",
        type: 1,
        comboListName: "N/A",
        required: 1,
        hidden: 0,
        readOnly: 0,
        i18nGroupName: "Financial Details",
        mimeType: "text/plain",
        jdbcType: JDBC_TYPE.DecimalInput,
        auditable: 1,
        exitClassId: "exitClass_007",
        exitClassDataId: "exitData_007",
        instanceId: "inst_129",
        textValue: "",
        numericValue: "99.99",
      },
      doc_upload: {
        id: "var_8",
        tokenId: 108,
        i18nName: "Upload Passport",
        type: 1,
        comboListName: "N/A",
        required: 1,
        hidden: 0,
        readOnly: 0,
        i18nGroupName: "Documents",
        mimeType: "application/pdf",
        jdbcType: JDBC_TYPE.UploadDocument,
        auditable: 1,
        exitClassId: "exitClass_008",
        exitClassDataId: "exitData_008",
        instanceId: "inst_130",
        textValue: "",
        numericValue: "",
      },
      url_field: {
        id: "var_9",
        tokenId: 109,
        i18nName: "Profile URL",
        type: 1,
        comboListName: "N/A",
        required: 0,
        hidden: 0,
        readOnly: 1,
        i18nGroupName: "External Links",
        mimeType: "text/plain",
        jdbcType: JDBC_TYPE.URL,
        auditable: 1,
        exitClassId: "exitClass_009",
        exitClassDataId: "exitData_009",
        instanceId: "inst_131",
        textValue: "https://example.com",
        numericValue: "",
      },
    },
    variablesByName: {
      dolore_c: "example_value",
    },
  };
}
